---
name: CI

on:
  push:
    tags: ["release/v*"]
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    name: "Test with Pytest"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv-sh
          echo "echo 'About to run /usr/local/bin/virtualenv-sh.sh'" >> ${HOME}/.bashrc
          echo ". /usr/local/bin/virtualenv-sh.bash" >> ${HOME}/.bashrc
          echo "WORKON_HOME=${HOME}/.virtualenvs" >> ${HOME}/.bashrc
          python -m pip install .[test]
      - name: "Run Pytest"
        run: |
          export VENV_MANAGEMENT_INTERACTIVE_SHELL=yes
          python -m pytest tests

  package:
    name: "Build Package Distributions"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Build distribution"
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
      - name: "Check wheel contents"
        run: |
          python -m pip install check-wheel-contents
          check-wheel-contents dist/*.whl
      - name: "Check long description is renderable"
        run: |
          python -m pip install twine
          python -m twine check dist/*
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/release/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
